/**
 * Single source of truth for site-wide metadata, branding, navigation, and
 * business / contact information. Imported by SEO helpers, Header, Footer,
 * sitemap, robots, JSON-LD structured data, and contact pages.
 *
 * Centralizing here keeps the codebase DRY (Single Responsibility, Open/Closed):
 * changing the phone number, company name, or canonical URL is a one-line edit
 * that propagates everywhere.
 */

const FALLBACK_SITE_URL = "https://friendsadvertising.in";

/** Resolve the canonical site URL — env-driven with safe fallback. */
function resolveSiteUrl(): string {
  const raw =
    process.env.NEXT_PUBLIC_SITE_URL ||
    (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : "") ||
    FALLBACK_SITE_URL;
  // Strip trailing slash so we can safely concatenate paths.
  return raw.replace(/\/+$/, "");
}

export const siteConfig = {
  name: "Friends Advertising",
  shortName: "Friends Adv",
  legalName: "Friends Advertising",
  tagline: "The Complete Outdoor Solution",
  description:
    "Premium outdoor advertising across Mumbai, Navi Mumbai, Pune and the rest of Maharashtra. Flex hoardings, LED & glow signs, transit media, and end-to-end campaign delivery.",
  keywords: [
    "outdoor advertising",
    "OOH advertising Mumbai",
    "billboards Maharashtra",
    "flex board printing",
    "LED signs",
    "transit advertising",
    "hoardings Navi Mumbai",
    "advertising agency Pune",
    "Friends Advertising",
  ],
  url: resolveSiteUrl(),
  locale: "en_IN",
  language: "en",
  themeColor: "#0071e3",
  contact: {
    email: "Friendsoutdoor@gmail.com",
    phone: "+91 98903 11234",
    phoneRaw: "+919890311234",
    address1: {
      city: "Navi Mumbai",
      region: "Maharashtra",
      country: "IN",
    },
    address2: {
      city: "Satara",
      region: "Maharashtra",
      country: "IN",
    },
  },
  social: {
    twitter: "@friendsadv",
  },
  /**
   * Open-Graph preview image (LinkedIn / WhatsApp / X / Slack link cards).
   * 1200×630 hero generated by `scripts/generate-og.mjs` — composites the
   * brand mark onto a navy gradient backdrop. Re-run the script after any
   * brand / tagline change.
   */
  defaultOgImage: "/media/og-default.jpg",
  defaultOgImageDimensions: { width: 1200, height: 630 },
} as const;

export type SiteConfig = typeof siteConfig;

/** Absolute URL helper for canonical / OG / sitemap entries. */
export function absoluteUrl(path: string = "/"): string {
  if (!path.startsWith("/")) path = `/${path}`;
  return `${siteConfig.url}${path}`;
}
